DROP TABLE BOARD_T;
CREATE TABLE BOARD_T (
  BOARD_NO    NUMBER NOT NULL,
  TITLE       VARCHAR2(1000 BYTE) NOT NULL,
  CONTENT     CLOB,
  MODIFIED_AT DATE,
  CREATED_AT  DATE,
  CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

--SELECT A.RN, A.*
--  FROM (SELECT ROW_NUMBER() OVER (ORDER BY EMPLOYEE_ID DESC) AS RN, *
--            FROM EMPLOYEES)A
-- WHERE A.RN BETWEEN 1 AND 20;
 
 SELECT A.BOARD_NO, A.TITLE, A.CONTENT, A.MODIFIED_AT, A.CREATED_AT
   FROM (SELECT ROW_NUMBER() OVER (ORDER BY BOARD_NO DESC) AS RN, BOARD_NO, TITLE, CONTENT, MODIFIED_AT, CREATED_AT
          FROM BOARD_T) A
  WHERE A.RN BETWEEN 1 AND 1;