DROP TABLE ARTICLE_T;
CREATE TABLE ARTICLE_T (
     ARTICLE_NO   NUMBER NOT NULL
    ,TITLE        VARCHAR2(1000 BYTE) NOT NULL
    ,CONTENT      CLOB
    ,EDITOR       VARCHAR2(1000 BYTE) NOT NULL
    ,HIT          NUMBER
    ,LASTMODIFIED DATE
    ,CREATED      DATE
    ,CONSTRAINT PK_ARTICLE PRIMARY KEY(ARTICLE_NO)
);
    
DROP SEQUENCE ARTICLE_SEQ;
CREATE SEQUENCE ARTICLE_SEQ NOCACHE;
